# Generated by Django 3.0.8 on 2020-07-10 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره نامه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ نامه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='docs/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='document',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گیرنده'),
        ),
        migrations.AlterField(
            model_name='document',
            name='requester',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متقاضی'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subsystem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرمجموعه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typ',
            field=models.IntegerField(choices=[(1, 'عمومی'), (2, 'شخصی')], default=1, verbose_name='نوع درخواست'),
        ),
    ]
